apiVersion: apps/v1
kind: Deployment
metadata:
  name:  twit-scraper
  namespace: twit-insigths
  labels:
    app:  twit-insigths
spec:
  selector:
    matchLabels:
      app: twit-insigths
      sub-app: twit-scraper
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: twit-insigths
        sub-app: twit-scraper
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  twit-scraper
        image:  ghcr.io/sthuck/scraper:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 256Mi
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /scraper/_health
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: db-conn
              key: user
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: db-conn
              key: password
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: twit-api
              key: api-key
        - name: MONGO_HOST
          value: mongodb.twit-insigths
        - name: MONGO_PORT
          value: "27017"
        ports:
        - containerPort:  3000
      restartPolicy: Always