apiVersion: v1
kind: Service
metadata:
  name: mongodb-test
  namespace: twit-insigths
spec:
  selector:
      app: twitter-insights
      component: db
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: mongodb
    protocol: TCP
    port: 27017
    targetPort: 27017

# nodeport for minikube